version: '3'

volumes:
  # MySQL Data
  mysql-data:
    driver: local
  # Redis Data
  redis-data:
    driver: local

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: vanhack-mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=vanhack_root_pass
      - MYSQL_DATABASE=vanhack
      - MYSQL_USER=vanhack_user
      - MYSQL_PASSWORD=vanhack_pass

  cache:
    image: ambientum/redis:4.0
    container_name: vanhack-cache
    command: --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Nginx)
  app:
    image: ambientum/php:7.2-nginx
    container_name: vanhack-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.2
    container_name: vanhack-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache
